// Author: kelexine <https://github.com/kelexine>
// Date: 2026-09-04
// Purpose: Single-pass filesystem scanner, privilege widening, and target aggregator

pub mod size;
pub mod sources;

pub use size::{
    calculate_dir_size, count_and_size_dir, parse_human_size, parse_journal_disk_usage,
};
pub use sources::*;

use crate::clean::classifier::artifacts::{is_build_artifact_dir, is_build_artifact_file};
use crate::clean::classifier::hotspots::{HotspotTracker, MAX_HOTSPOTS};
use crate::clean::classifier::logs_cache::{is_stale_cache_entry, is_stale_log_file};
use crate::clean::classifier::{CleanCategory, CleanItem, CleanTarget};
use crate::clean::privilege::{ELEVATED_SYSTEM_ROOTS, is_elevated, is_writable};
use crate::config::CleanConfig;
use ignore::{WalkBuilder, WalkState};
use std::collections::{HashMap, HashSet};
use std::path::PathBuf;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Arc, Mutex};

/// Report generated by running a clean scan across configured roots.
#[derive(Debug, Default, Clone)]
pub struct CleanReport {
    /// High-level aggregated cleanup targets presented to user.
    pub targets: Vec<CleanTarget>,
    /// Flattened items maintained for inspection and legacy compatibility.
    pub items: Vec<CleanItem>,
    pub skipped_permission_denied: usize,
    pub is_elevated: bool,
}

impl CleanReport {
    #[must_use]
    pub fn total_reclaimable_bytes(&self) -> u64 {
        if !self.targets.is_empty() {
            self.targets.iter().map(|t| t.size_bytes).sum()
        } else {
            self.items.iter().map(|i| i.size_bytes).sum()
        }
    }

    #[must_use]
    pub fn total_item_count(&self) -> usize {
        if !self.targets.is_empty() {
            self.targets.iter().map(|t| t.item_count).sum()
        } else {
            self.items.len()
        }
    }
}

/// Performs a unified filesystem scan and aggregates clean targets.
#[must_use]
pub fn scan_hygiene(config: &CleanConfig) -> CleanReport {
    let elevated = is_elevated();
    let mut targets: Vec<CleanTarget> = Vec::new();
    let mut handled_paths: HashSet<PathBuf> = HashSet::new();

    // 1. Gather all roots, widening when elevated (ADR-0001 §2.3)
    let mut roots: Vec<PathBuf> = config
        .scan_roots
        .iter()
        .chain(config.extra_scan_roots.iter())
        .filter(|p| p.exists())
        .cloned()
        .collect();

    // Exclude development workspaces explicitly (out of bounds for hygiene cleaner)
    if let Some(home_path) = crate::config::resolve_home_dir() {
        let dev_dir = home_path.join("dev");
        let projects_dir = home_path.join("projects");
        roots.retain(|r| {
            r != &dev_dir
                && r != &projects_dir
                && !r.starts_with(&dev_dir)
                && !r.starts_with(&projects_dir)
        });
    }

    if elevated {
        for extra in ELEVATED_SYSTEM_ROOTS {
            let p = PathBuf::from(extra);
            if p.exists() && !roots.contains(&p) {
                roots.push(p);
            }
        }
    }

    if roots.is_empty() {
        return CleanReport {
            is_elevated: elevated,
            ..Default::default()
        };
    }

    // 2. Pre-scan well-known batch targets to avoid UI spam from thousands of individual files
    for root in &roots {
        let path_str = root.to_string_lossy();

        if path_str.contains("pacman/pkg") {
            if let Some(target) = scan_pacman_cache(root) {
                handled_paths.insert(root.clone());
                targets.push(target);
            }
        } else if path_str.ends_with(".cache") || path_str.ends_with("/.cache") {
            let cache_targets = scan_user_cache_root(root, config.age_threshold_days);
            for ct in cache_targets {
                handled_paths.insert(ct.path.clone());
                targets.push(ct);
            }
            handled_paths.insert(root.clone());
        } else if path_str.ends_with("Trash") || path_str.contains("/Trash") {
            if let Some(target) = scan_trash(root) {
                handled_paths.insert(root.clone());
                targets.push(target);
            }
        } else if path_str.contains(".dotfiles_backup") {
            let backup_targets = scan_dotfiles_backups(root, config.age_threshold_days);
            for bt in backup_targets {
                handled_paths.insert(bt.path.clone());
                targets.push(bt);
            }
        }
    }

    if let Some(journal_target) = scan_journal_logs() {
        handled_paths.insert(journal_target.path.clone());
        targets.push(journal_target);
    }

    #[derive(Default)]
    struct LooseBucket {
        size_bytes: u64,
        count: usize,
        files: Vec<PathBuf>,
    }

    type LooseBucketMap = HashMap<(CleanCategory, PathBuf), LooseBucket>;

    // 3. Setup WalkBuilder for general tree scan on unhandled roots (temp dirs, custom roots)
    let unhandled_roots: Vec<PathBuf> = roots
        .iter()
        .filter(|r| !handled_paths.contains(*r))
        .cloned()
        .collect();

    let tracker = Arc::new(Mutex::new(HotspotTracker::new(MAX_HOTSPOTS)));
    let permission_denied = Arc::new(AtomicUsize::new(0));

    if !unhandled_roots.is_empty() {
        let first_root = unhandled_roots[0].clone();
        let mut builder = WalkBuilder::new(&first_root);
        for r in &unhandled_roots[1..] {
            builder.add(r);
        }

        for exc in &config.exclude {
            builder.add_custom_ignore_filename(exc);
        }

        builder.hidden(false).parents(false).git_ignore(true);

        let found_targets = Arc::new(Mutex::new(Vec::new()));
        let loose_buckets: Arc<Mutex<LooseBucketMap>> = Arc::new(Mutex::new(HashMap::new()));

        let targets_clone = Arc::clone(&found_targets);
        let tracker_clone = Arc::clone(&tracker);
        let perm_clone = Arc::clone(&permission_denied);
        let handled_clone = Arc::new(handled_paths);
        let loose_clone = Arc::clone(&loose_buckets);
        let age_threshold = config.age_threshold_days;

        builder.build_parallel().run(|| {
            let targets_ref = Arc::clone(&targets_clone);
            let tracker = Arc::clone(&tracker_clone);
            let perm = Arc::clone(&perm_clone);
            let handled = Arc::clone(&handled_clone);
            let loose = Arc::clone(&loose_clone);

            Box::new(move |result| match result {
                Ok(entry) => {
                    let path = entry.path();

                    // Skip directories/files already covered by specialized targets
                    for h in handled.iter() {
                        if path.starts_with(h) {
                            return WalkState::Skip;
                        }
                    }

                    let meta = match entry.metadata() {
                        Ok(m) => m,
                        Err(err) => {
                            if err
                                .io_error()
                                .is_some_and(|e| e.kind() == std::io::ErrorKind::PermissionDenied)
                            {
                                perm.fetch_add(1, Ordering::Relaxed);
                            }
                            return WalkState::Continue;
                        }
                    };

                    if meta.is_dir() {
                        if is_build_artifact_dir(path) {
                            let (size, count) = count_and_size_dir(path);
                            let title = format_build_target_title(path);
                            let requires_elevation = !is_writable(path);

                            if let Ok(mut list) = targets_ref.lock() {
                                list.push(CleanTarget::new(
                                    title,
                                    path.to_path_buf(),
                                    CleanCategory::Artifacts,
                                    size,
                                    count.max(1),
                                    requires_elevation,
                                    true,
                                    Vec::new(),
                                    format!("Build artifact tree: {}", path.display()),
                                ));
                            }
                            return WalkState::Skip;
                        }

                        // Special temp caches (e.g. ghidra packed-db-cache)
                        let p_str = path.to_string_lossy();
                        if p_str.contains("packed-db-cache") || p_str.contains("ghidra") {
                            let (size, count) = count_and_size_dir(path);
                            if count > 0 {
                                if let Ok(mut list) = targets_ref.lock() {
                                    list.push(CleanTarget::new(
                                        "Ghidra Database Cache".to_string(),
                                        path.to_path_buf(),
                                        CleanCategory::LogsCache,
                                        size,
                                        count,
                                        !is_writable(path),
                                        true,
                                        Vec::new(),
                                        "Temporary Ghidra unpacked database cache".to_string(),
                                    ));
                                }
                                return WalkState::Skip;
                            }
                        }
                    } else if meta.is_file() {
                        let size = meta.len();
                        if let Ok(mut tr) = tracker.lock() {
                            tr.observe(path, size);
                        }

                        let base_dir = path
                            .parent()
                            .map(|p| p.to_path_buf())
                            .unwrap_or_else(|| path.to_path_buf());

                        if is_build_artifact_file(path) {
                            if let Ok(mut map) = loose.lock() {
                                let entry =
                                    map.entry((CleanCategory::Artifacts, base_dir)).or_default();
                                entry.size_bytes += size;
                                entry.count += 1;
                                entry.files.push(path.to_path_buf());
                            }
                        } else if (is_stale_log_file(path, &meta, age_threshold)
                            || is_stale_cache_entry(path, &meta, age_threshold))
                            && let Ok(mut map) = loose.lock()
                        {
                            let entry =
                                map.entry((CleanCategory::LogsCache, base_dir)).or_default();
                            entry.size_bytes += size;
                            entry.count += 1;
                            entry.files.push(path.to_path_buf());
                        }
                    }
                    WalkState::Continue
                }
                Err(err) => {
                    if err
                        .io_error()
                        .is_some_and(|e| e.kind() == std::io::ErrorKind::PermissionDenied)
                    {
                        perm.fetch_add(1, Ordering::Relaxed);
                    }
                    WalkState::Continue
                }
            })
        });

        let extra_targets = targets_clone
            .lock()
            .map_or_else(|_| Vec::new(), |guard| guard.clone());
        targets.extend(extra_targets);

        if let Ok(buckets) = loose_buckets.lock() {
            for ((category, base_dir), bucket) in buckets.iter() {
                if bucket.count > 0 {
                    let dir_name = base_dir
                        .file_name()
                        .and_then(|s| s.to_str())
                        .unwrap_or("temporary");
                    let title = match category {
                        CleanCategory::Artifacts => format!("Compiled Artifacts ({dir_name})"),
                        CleanCategory::LogsCache => format!("Stale Logs & Temp ({dir_name})"),
                        _ => format!("Loose Files ({})", base_dir.display()),
                    };
                    targets.push(CleanTarget::new(
                        title,
                        base_dir.clone(),
                        *category,
                        bucket.size_bytes,
                        bucket.count,
                        !is_writable(base_dir),
                        false,
                        bucket.files.clone(),
                        format!("{} loose {category} file(s)", bucket.count),
                    ));
                }
            }
        }
    }

    // 4. Hotspots: only track standalone large files not already included in targets
    let hotspots = tracker
        .lock()
        .map_or_else(|_| Vec::new(), |guard| guard.clone().into_sorted_vec());
    for hot in hotspots {
        let is_already_covered = targets.iter().any(|t| {
            if t.is_tree {
                hot.path.starts_with(&t.path)
            } else {
                t.path == hot.path || t.files.contains(&hot.path)
            }
        });

        if !is_already_covered && hot.size_bytes >= 50 * 1024 * 1024 {
            let filename = hot
                .path
                .file_name()
                .map(|s| s.to_string_lossy().to_string())
                .unwrap_or_else(|| hot.path.display().to_string());
            targets.push(CleanTarget::new(
                format!("Large file hotspot: {filename}"),
                hot.path.clone(),
                CleanCategory::Hotspots,
                hot.size_bytes,
                1,
                !is_writable(&hot.path),
                false,
                vec![hot.path.clone()],
                "Disk hotspot (top size consumer)".to_string(),
            ));
        }
    }

    // Sort targets by size descending so top reclaimable targets are prioritized
    targets.sort_by_key(|a| std::cmp::Reverse(a.size_bytes));

    // 5. Build legacy CleanItem list for backwards compatibility
    let mut items: Vec<CleanItem> = Vec::new();
    for t in &targets {
        if !t.files.is_empty() {
            for f in &t.files {
                items.push(CleanItem::new(
                    f.clone(),
                    t.size_bytes / (t.files.len() as u64).max(1),
                    t.category,
                    t.reason.clone(),
                    false,
                ));
            }
        } else {
            items.push(CleanItem::new(
                t.path.clone(),
                t.size_bytes,
                t.category,
                t.reason.clone(),
                t.is_tree,
            ));
        }
    }

    CleanReport {
        targets,
        items,
        skipped_permission_denied: permission_denied.load(Ordering::Relaxed),
        is_elevated: elevated,
    }
}
