// Author: kelexine <https://github.com/kelexine>
// Date: 2026-09-04
// Purpose: Single-pass filesystem scanner, privilege widening, and target aggregator

use crate::clean::classifier::artifacts::{is_build_artifact_dir, is_build_artifact_file};
use crate::clean::classifier::hotspots::{HotspotTracker, MAX_HOTSPOTS};
use crate::clean::classifier::logs_cache::{
    is_older_than, is_stale_cache_entry, is_stale_log_file,
};
use crate::clean::classifier::{CleanCategory, CleanItem, CleanTarget};
use crate::clean::privilege::{ELEVATED_SYSTEM_ROOTS, is_elevated, is_writable};
use crate::config::CleanConfig;
use ignore::{WalkBuilder, WalkState};
use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Arc, Mutex};

/// Report generated by running a clean scan across configured roots.
#[derive(Debug, Default, Clone)]
pub struct CleanReport {
    /// High-level aggregated cleanup targets presented to user.
    pub targets: Vec<CleanTarget>,
    /// Flattened items maintained for inspection and legacy compatibility.
    pub items: Vec<CleanItem>,
    pub skipped_permission_denied: usize,
    pub is_elevated: bool,
}

impl CleanReport {
    #[must_use]
    pub fn total_reclaimable_bytes(&self) -> u64 {
        if !self.targets.is_empty() {
            self.targets.iter().map(|t| t.size_bytes).sum()
        } else {
            self.items.iter().map(|i| i.size_bytes).sum()
        }
    }

    #[must_use]
    pub fn total_item_count(&self) -> usize {
        if !self.targets.is_empty() {
            self.targets.iter().map(|t| t.item_count).sum()
        } else {
            self.items.len()
        }
    }
}

/// Recursively computes directory size in bytes.
#[must_use]
pub fn calculate_dir_size(path: &Path) -> u64 {
    let (size, _) = count_and_size_dir(path);
    size
}

/// Computes total size and item count within a directory tree.
#[must_use]
pub fn count_and_size_dir(path: &Path) -> (u64, usize) {
    let mut total_size: u64 = 0;
    let mut count: usize = 0;

    if let Ok(entries) = fs::read_dir(path) {
        for entry in entries.flatten() {
            let p = entry.path();
            if let Ok(meta) = entry.metadata() {
                if meta.is_dir() {
                    let (sub_size, sub_count) = count_and_size_dir(&p);
                    total_size += sub_size;
                    count += sub_count;
                } else {
                    total_size += meta.len();
                    count += 1;
                }
            }
        }
    }

    (total_size, count)
}

/// Performs a unified filesystem scan and aggregates clean targets.
#[must_use]
pub fn scan_hygiene(config: &CleanConfig) -> CleanReport {
    let elevated = is_elevated();
    let mut targets: Vec<CleanTarget> = Vec::new();
    let mut handled_paths: HashSet<PathBuf> = HashSet::new();

    // 1. Gather all roots, widening when elevated (ADR-0001 §2.3)
    let mut roots: Vec<PathBuf> = config
        .scan_roots
        .iter()
        .chain(config.extra_scan_roots.iter())
        .filter(|p| p.exists())
        .cloned()
        .collect();

    // Exclude development workspaces explicitly (out of bounds for hygiene cleaner)
    if let Some(home_path) = crate::config::resolve_home_dir() {
        let dev_dir = home_path.join("dev");
        let projects_dir = home_path.join("projects");
        roots.retain(|r| {
            r != &dev_dir
                && r != &projects_dir
                && !r.starts_with(&dev_dir)
                && !r.starts_with(&projects_dir)
        });
    }

    if elevated {
        for extra in ELEVATED_SYSTEM_ROOTS {
            let p = PathBuf::from(extra);
            if p.exists() && !roots.contains(&p) {
                roots.push(p);
            }
        }
    }

    if roots.is_empty() {
        return CleanReport {
            is_elevated: elevated,
            ..Default::default()
        };
    }

    // 2. Pre-scan well-known batch targets to avoid UI spam from thousands of individual files
    for root in &roots {
        let path_str = root.to_string_lossy();

        if path_str.contains("pacman/pkg") {
            if let Some(target) = scan_pacman_cache(root) {
                handled_paths.insert(root.clone());
                targets.push(target);
            }
        } else if path_str.ends_with(".cache") || path_str.ends_with("/.cache") {
            let cache_targets = scan_user_cache_root(root, config.age_threshold_days);
            for ct in cache_targets {
                handled_paths.insert(ct.path.clone());
                targets.push(ct);
            }
            handled_paths.insert(root.clone());
        } else if path_str.ends_with("Trash") || path_str.contains("/Trash") {
            if let Some(target) = scan_trash(root) {
                handled_paths.insert(root.clone());
                targets.push(target);
            }
        } else if path_str.contains(".dotfiles_backup") {
            let backup_targets = scan_dotfiles_backups(root, config.age_threshold_days);
            for bt in backup_targets {
                handled_paths.insert(bt.path.clone());
                targets.push(bt);
            }
        }
    }

    if let Some(journal_target) = scan_journal_logs() {
        handled_paths.insert(journal_target.path.clone());
        targets.push(journal_target);
    }

    #[derive(Default)]
    struct LooseBucket {
        size_bytes: u64,
        count: usize,
        files: Vec<PathBuf>,
    }

    type LooseBucketMap = HashMap<(CleanCategory, PathBuf), LooseBucket>;

    // 3. Setup WalkBuilder for general tree scan on unhandled roots (temp dirs, custom roots)
    let unhandled_roots: Vec<PathBuf> = roots
        .iter()
        .filter(|r| !handled_paths.contains(*r))
        .cloned()
        .collect();

    let tracker = Arc::new(Mutex::new(HotspotTracker::new(MAX_HOTSPOTS)));
    let permission_denied = Arc::new(AtomicUsize::new(0));

    if !unhandled_roots.is_empty() {
        let first_root = unhandled_roots[0].clone();
        let mut builder = WalkBuilder::new(&first_root);
        for r in &unhandled_roots[1..] {
            builder.add(r);
        }

        for exc in &config.exclude {
            builder.add_custom_ignore_filename(exc);
        }

        builder.hidden(false).parents(false).git_ignore(true);

        let found_targets = Arc::new(Mutex::new(Vec::new()));
        let loose_buckets: Arc<Mutex<LooseBucketMap>> = Arc::new(Mutex::new(HashMap::new()));

        let targets_clone = Arc::clone(&found_targets);
        let tracker_clone = Arc::clone(&tracker);
        let perm_clone = Arc::clone(&permission_denied);
        let handled_clone = Arc::new(handled_paths);
        let loose_clone = Arc::clone(&loose_buckets);
        let age_threshold = config.age_threshold_days;

        builder.build_parallel().run(|| {
            let targets_ref = Arc::clone(&targets_clone);
            let tracker = Arc::clone(&tracker_clone);
            let perm = Arc::clone(&perm_clone);
            let handled = Arc::clone(&handled_clone);
            let loose = Arc::clone(&loose_clone);

            Box::new(move |result| match result {
                Ok(entry) => {
                    let path = entry.path();

                    // Skip directories/files already covered by specialized targets
                    for h in handled.iter() {
                        if path.starts_with(h) {
                            return WalkState::Skip;
                        }
                    }

                    let meta = match entry.metadata() {
                        Ok(m) => m,
                        Err(err) => {
                            if err
                                .io_error()
                                .is_some_and(|e| e.kind() == std::io::ErrorKind::PermissionDenied)
                            {
                                perm.fetch_add(1, Ordering::Relaxed);
                            }
                            return WalkState::Continue;
                        }
                    };

                    if meta.is_dir() {
                        if is_build_artifact_dir(path) {
                            let (size, count) = count_and_size_dir(path);
                            let title = format_build_target_title(path);
                            let requires_elevation = !is_writable(path);

                            if let Ok(mut list) = targets_ref.lock() {
                                list.push(CleanTarget::new(
                                    title,
                                    path.to_path_buf(),
                                    CleanCategory::Artifacts,
                                    size,
                                    count.max(1),
                                    requires_elevation,
                                    true,
                                    Vec::new(),
                                    format!("Build artifact tree: {}", path.display()),
                                ));
                            }
                            return WalkState::Skip;
                        }

                        // Special temp caches (e.g. ghidra packed-db-cache)
                        let p_str = path.to_string_lossy();
                        if p_str.contains("packed-db-cache") || p_str.contains("ghidra") {
                            let (size, count) = count_and_size_dir(path);
                            if count > 0 {
                                if let Ok(mut list) = targets_ref.lock() {
                                    list.push(CleanTarget::new(
                                        "Ghidra Database Cache".to_string(),
                                        path.to_path_buf(),
                                        CleanCategory::LogsCache,
                                        size,
                                        count,
                                        !is_writable(path),
                                        true,
                                        Vec::new(),
                                        "Temporary Ghidra unpacked database cache".to_string(),
                                    ));
                                }
                                return WalkState::Skip;
                            }
                        }
                    } else if meta.is_file() {
                        let size = meta.len();
                        if let Ok(mut tr) = tracker.lock() {
                            tr.observe(path, size);
                        }

                        let base_dir = path
                            .parent()
                            .map(|p| p.to_path_buf())
                            .unwrap_or_else(|| path.to_path_buf());

                        if is_build_artifact_file(path) {
                            if let Ok(mut map) = loose.lock() {
                                let entry =
                                    map.entry((CleanCategory::Artifacts, base_dir)).or_default();
                                entry.size_bytes += size;
                                entry.count += 1;
                                entry.files.push(path.to_path_buf());
                            }
                        } else if (is_stale_log_file(path, &meta, age_threshold)
                            || is_stale_cache_entry(path, &meta, age_threshold))
                            && let Ok(mut map) = loose.lock()
                        {
                            let entry =
                                map.entry((CleanCategory::LogsCache, base_dir)).or_default();
                            entry.size_bytes += size;
                            entry.count += 1;
                            entry.files.push(path.to_path_buf());
                        }
                    }
                    WalkState::Continue
                }
                Err(err) => {
                    if err
                        .io_error()
                        .is_some_and(|e| e.kind() == std::io::ErrorKind::PermissionDenied)
                    {
                        perm.fetch_add(1, Ordering::Relaxed);
                    }
                    WalkState::Continue
                }
            })
        });

        let extra_targets = targets_clone
            .lock()
            .map_or_else(|_| Vec::new(), |guard| guard.clone());
        targets.extend(extra_targets);

        if let Ok(buckets) = loose_buckets.lock() {
            for ((category, base_dir), bucket) in buckets.iter() {
                if bucket.count > 0 {
                    let dir_name = base_dir
                        .file_name()
                        .and_then(|s| s.to_str())
                        .unwrap_or("temporary");
                    let title = match category {
                        CleanCategory::Artifacts => format!("Compiled Artifacts ({dir_name})"),
                        CleanCategory::LogsCache => format!("Stale Logs & Temp ({dir_name})"),
                        _ => format!("Loose Files ({})", base_dir.display()),
                    };
                    targets.push(CleanTarget::new(
                        title,
                        base_dir.clone(),
                        *category,
                        bucket.size_bytes,
                        bucket.count,
                        !is_writable(base_dir),
                        false,
                        bucket.files.clone(),
                        format!("{} loose {category} file(s)", bucket.count),
                    ));
                }
            }
        }
    }

    // 4. Hotspots: only track standalone large files not already included in targets
    let hotspots = tracker
        .lock()
        .map_or_else(|_| Vec::new(), |guard| guard.clone().into_sorted_vec());
    for hot in hotspots {
        let is_already_covered = targets.iter().any(|t| {
            if t.is_tree {
                hot.path.starts_with(&t.path)
            } else {
                t.path == hot.path || t.files.contains(&hot.path)
            }
        });

        if !is_already_covered && hot.size_bytes >= 50 * 1024 * 1024 {
            let filename = hot
                .path
                .file_name()
                .map(|s| s.to_string_lossy().to_string())
                .unwrap_or_else(|| hot.path.display().to_string());
            targets.push(CleanTarget::new(
                format!("Large file hotspot: {filename}"),
                hot.path.clone(),
                CleanCategory::Hotspots,
                hot.size_bytes,
                1,
                !is_writable(&hot.path),
                false,
                vec![hot.path.clone()],
                "Disk hotspot (top size consumer)".to_string(),
            ));
        }
    }

    // Sort targets by size descending so top reclaimable targets are prioritized
    targets.sort_by_key(|a| std::cmp::Reverse(a.size_bytes));

    // 5. Build legacy CleanItem list for backwards compatibility
    let mut items: Vec<CleanItem> = Vec::new();
    for t in &targets {
        if !t.files.is_empty() {
            for f in &t.files {
                items.push(CleanItem::new(
                    f.clone(),
                    t.size_bytes / (t.files.len() as u64).max(1),
                    t.category,
                    t.reason.clone(),
                    false,
                ));
            }
        } else {
            items.push(CleanItem::new(
                t.path.clone(),
                t.size_bytes,
                t.category,
                t.reason.clone(),
                t.is_tree,
            ));
        }
    }

    CleanReport {
        targets,
        items,
        skipped_permission_denied: permission_denied.load(Ordering::Relaxed),
        is_elevated: elevated,
    }
}

/// Formats a readable title for a build target directory.
fn format_build_target_title(path: &Path) -> String {
    let name = path
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("target");
    let project = path
        .parent()
        .and_then(|p| p.file_name())
        .and_then(|s| s.to_str())
        .unwrap_or("project");

    match name {
        "target" => format!("Cargo Target ({project})"),
        "node_modules" => format!("node_modules ({project})"),
        "__pycache__" => format!("Python cache ({project})"),
        _ => format!("Build Artifact ({project}/{name})"),
    }
}

/// Scans /var/cache/pacman/pkg for cached packages and signatures.
fn scan_pacman_cache(pacman_dir: &Path) -> Option<CleanTarget> {
    if !pacman_dir.exists() {
        return None;
    }

    let entries = fs::read_dir(pacman_dir).ok()?;
    let mut files = Vec::new();
    let mut total_size: u64 = 0;

    for entry in entries.flatten() {
        let path = entry.path();
        let name = match path.file_name().and_then(|s| s.to_str()) {
            Some(n) => n,
            None => continue,
        };

        let is_pkg = name.ends_with(".pkg.tar.zst")
            || name.ends_with(".pkg.tar.xz")
            || name.ends_with(".sig")
            || name.ends_with(".part");

        if is_pkg && let Ok(meta) = entry.metadata() {
            total_size += meta.len();
            files.push(path);
        }
    }

    if files.is_empty() {
        return None;
    }

    let count = files.len();
    Some(CleanTarget::new(
        "Pacman Package Cache".to_string(),
        pacman_dir.to_path_buf(),
        CleanCategory::PackageCache,
        total_size,
        count,
        !is_writable(pacman_dir),
        false,
        files,
        format!("{count} cached packages & signatures"),
    ))
}

/// Scans user Trash directory.
fn scan_trash(trash_dir: &Path) -> Option<CleanTarget> {
    if !trash_dir.exists() {
        return None;
    }

    let files_dir = trash_dir.join("files");
    let info_dir = trash_dir.join("info");
    let mut files = Vec::new();
    let mut total_size: u64 = 0;

    for dir in [&files_dir, &info_dir] {
        if let Ok(entries) = fs::read_dir(dir) {
            for entry in entries.flatten() {
                let p = entry.path();
                if let Ok(meta) = entry.metadata() {
                    if meta.is_dir() {
                        total_size += calculate_dir_size(&p);
                    } else {
                        total_size += meta.len();
                    }
                    files.push(p);
                }
            }
        }
    }

    if files.is_empty() {
        return None;
    }

    let count = files.len();
    Some(CleanTarget::new(
        "User Trash Bin".to_string(),
        trash_dir.to_path_buf(),
        CleanCategory::Trash,
        total_size,
        count,
        !is_writable(trash_dir),
        false,
        files,
        format!("{count} files in Trash"),
    ))
}

/// Scans direct subdirectories within ~/.cache and aggregates application caches.
fn scan_user_cache_root(cache_root: &Path, age_threshold: u64) -> Vec<CleanTarget> {
    let mut targets = Vec::new();
    let entries = match fs::read_dir(cache_root) {
        Ok(e) => e,
        Err(_) => return targets,
    };

    for entry in entries.flatten() {
        let p = entry.path();
        let meta = match entry.metadata() {
            Ok(m) => m,
            Err(_) => continue,
        };

        if !meta.is_dir() {
            continue;
        }

        let name = match p.file_name().and_then(|s| s.to_str()) {
            Some(n) => n,
            None => continue,
        };

        let (size, count) = count_and_size_dir(&p);
        if count == 0 || size < 1024 {
            continue;
        }

        let requires_elevation = !is_writable(&p);

        match name {
            "thumbnails" => {
                targets.push(CleanTarget::new(
                    "User Thumbnail Cache".to_string(),
                    p,
                    CleanCategory::Thumbnails,
                    size,
                    count,
                    requires_elevation,
                    true,
                    Vec::new(),
                    format!("{count} cached image thumbnails"),
                ));
            }
            "yay" => {
                targets.push(CleanTarget::new(
                    "Yay AUR Build Cache".to_string(),
                    p,
                    CleanCategory::PackageCache,
                    size,
                    count,
                    requires_elevation,
                    true,
                    Vec::new(),
                    format!("{count} build artifacts & packages"),
                ));
            }
            "paru" => {
                targets.push(CleanTarget::new(
                    "Paru AUR Build Cache".to_string(),
                    p,
                    CleanCategory::PackageCache,
                    size,
                    count,
                    requires_elevation,
                    true,
                    Vec::new(),
                    format!("{count} build artifacts & packages"),
                ));
            }
            "uv" => {
                targets.push(CleanTarget::new(
                    "uv Python Cache".to_string(),
                    p,
                    CleanCategory::PackageCache,
                    size,
                    count,
                    requires_elevation,
                    true,
                    Vec::new(),
                    format!("{count} cached Python packages & wheels"),
                ));
            }
            "pip" => {
                targets.push(CleanTarget::new(
                    "pip Cache".to_string(),
                    p,
                    CleanCategory::PackageCache,
                    size,
                    count,
                    requires_elevation,
                    true,
                    Vec::new(),
                    format!("{count} cached pip wheels"),
                ));
            }
            "ccache" => {
                targets.push(CleanTarget::new(
                    "ccache Compiler Cache".to_string(),
                    p,
                    CleanCategory::LogsCache,
                    size,
                    count,
                    requires_elevation,
                    true,
                    Vec::new(),
                    format!("{count} compiled objects"),
                ));
            }
            "google-chrome" => {
                targets.push(CleanTarget::new(
                    "Google Chrome Cache".to_string(),
                    p,
                    CleanCategory::LogsCache,
                    size,
                    count,
                    requires_elevation,
                    true,
                    Vec::new(),
                    format!("{count} browser cache files"),
                ));
            }
            "BraveSoftware" => {
                targets.push(CleanTarget::new(
                    "Brave Browser Cache".to_string(),
                    p,
                    CleanCategory::LogsCache,
                    size,
                    count,
                    requires_elevation,
                    true,
                    Vec::new(),
                    format!("{count} browser cache files"),
                ));
            }
            "go-build" => {
                targets.push(CleanTarget::new(
                    "Go Build Cache".to_string(),
                    p,
                    CleanCategory::LogsCache,
                    size,
                    count,
                    requires_elevation,
                    true,
                    Vec::new(),
                    format!("{count} cached Go build targets"),
                ));
            }
            "flatpak" => {
                targets.push(CleanTarget::new(
                    "Flatpak Cache".to_string(),
                    p,
                    CleanCategory::LogsCache,
                    size,
                    count,
                    requires_elevation,
                    true,
                    Vec::new(),
                    format!("{count} flatpak cache entries"),
                ));
            }
            _ => {
                if is_older_than(&meta, age_threshold) && size >= 10 * 1024 * 1024 {
                    targets.push(CleanTarget::new(
                        format!("App Cache ({name})"),
                        p,
                        CleanCategory::LogsCache,
                        size,
                        count,
                        requires_elevation,
                        true,
                        Vec::new(),
                        format!("Cache older than {age_threshold} days"),
                    ));
                }
            }
        }
    }

    targets
}

/// Scans stale dotfiles backup snapshot subfolders.
fn scan_dotfiles_backups(backup_dir: &Path, age_threshold: u64) -> Vec<CleanTarget> {
    let mut targets = Vec::new();
    if !backup_dir.exists() {
        return targets;
    }

    if let Ok(entries) = fs::read_dir(backup_dir) {
        for entry in entries.flatten() {
            let p = entry.path();
            if let Ok(meta) = entry.metadata()
                && meta.is_dir()
                && is_older_than(&meta, age_threshold)
            {
                let (size, count) = count_and_size_dir(&p);
                let name = p.file_name().and_then(|s| s.to_str()).unwrap_or("backup");
                targets.push(CleanTarget::new(
                    format!("Stale Dotfiles Backup ({name})"),
                    p.clone(),
                    CleanCategory::Backups,
                    size,
                    count,
                    !is_writable(&p),
                    true,
                    Vec::new(),
                    format!("Backup snapshot older than {age_threshold} days"),
                ));
            }
        }
    }

    targets
}

/// Parses human size string (e.g. "52.4M", "1.2G", "800K") into bytes.
fn parse_human_size(s: &str) -> Option<u64> {
    let s = s.trim();
    let num_end = s.find(|c: char| !c.is_ascii_digit() && c != '.')?;
    let (num_part, unit_part) = s.split_at(num_end);
    let val: f64 = num_part.parse().ok()?;
    let unit = unit_part.to_uppercase();

    let multiplier = if unit.starts_with('K') {
        1024.0
    } else if unit.starts_with('M') {
        1024.0 * 1024.0
    } else if unit.starts_with('G') {
        1024.0 * 1024.0 * 1024.0
    } else if unit.starts_with('T') {
        1024.0 * 1024.0 * 1024.0 * 1024.0
    } else {
        1.0
    };

    Some((val * multiplier) as u64)
}

/// Parses the output of `journalctl --disk-usage`.
fn parse_journal_disk_usage(output: &str) -> Option<u64> {
    let take_up = output.find("take up ")?;
    let rest = &output[take_up + "take up ".len()..];
    let size_token = rest.split_whitespace().next()?;
    parse_human_size(size_token)
}

/// Scans systemd journal logs using /var/log/journal and journalctl --disk-usage.
fn scan_journal_logs() -> Option<CleanTarget> {
    let journal_dir = Path::new("/var/log/journal");
    if journal_dir.exists() {
        let (size, count) = count_and_size_dir(journal_dir);
        if size > 0 {
            return Some(CleanTarget::new(
                "Systemd Journal Logs".to_string(),
                journal_dir.to_path_buf(),
                CleanCategory::LogsCache,
                size,
                count.max(1),
                !is_writable(journal_dir),
                false,
                Vec::new(),
                "Archived journals (vacuum with: sudo journalctl --vacuum-time=14d)".to_string(),
            ));
        }
    }

    if let Ok(output) = std::process::Command::new("journalctl")
        .arg("--disk-usage")
        .output()
        && output.status.success()
    {
        let out_str = String::from_utf8_lossy(&output.stdout);
        if let Some(bytes) = parse_journal_disk_usage(&out_str)
            && bytes > 0
        {
            return Some(CleanTarget::new(
                "Systemd Journal Logs".to_string(),
                journal_dir.to_path_buf(),
                CleanCategory::LogsCache,
                bytes,
                1,
                true,
                false,
                Vec::new(),
                "Archived journals (vacuum with: sudo journalctl --vacuum-time=14d)".to_string(),
            ));
        }
    }

    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_human_size_and_journal_output() {
        assert_eq!(parse_human_size("1024K"), Some(1024 * 1024));
        assert_eq!(parse_human_size("50M"), Some(50 * 1024 * 1024));
        assert_eq!(parse_human_size("2G"), Some(2 * 1024 * 1024 * 1024));

        let sample = "Archived and active journals take up 52.4M in the file system.";
        let parsed = parse_journal_disk_usage(sample).expect("parsed journal disk usage");
        assert!(parsed > 50 * 1024 * 1024);
    }
}
