// Author: kelexine <https://github.com/kelexine>
// Date: 2026-09-04
// Purpose: Single-pass filesystem scanner and hygiene classifier

use crate::clean::classifier::artifacts::{is_build_artifact_dir, is_build_artifact_file};
use crate::clean::classifier::hotspots::{HotspotTracker, MAX_HOTSPOTS};
use crate::clean::classifier::logs_cache::{is_stale_cache_entry, is_stale_log_file};
use crate::clean::classifier::{CleanCategory, CleanItem};
use crate::clean::privilege::is_elevated;
use crate::config::CleanConfig;
use ignore::{WalkBuilder, WalkState};
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Arc, Mutex};

/// Report generated by running a clean scan across configured roots.
#[derive(Debug, Default, Clone)]
pub struct CleanReport {
    pub items: Vec<CleanItem>,
    pub skipped_permission_denied: usize,
    pub is_elevated: bool,
}

impl CleanReport {
    #[must_use]
    pub fn total_reclaimable_bytes(&self) -> u64 {
        self.items.iter().map(|item| item.size_bytes).sum()
    }
}

/// Recursively computes directory size in bytes.
#[must_use]
pub fn calculate_dir_size(path: &Path) -> u64 {
    let mut total: u64 = 0;
    if let Ok(entries) = fs::read_dir(path) {
        for entry in entries.flatten() {
            let p = entry.path();
            if let Ok(meta) = entry.metadata() {
                if meta.is_dir() {
                    total += calculate_dir_size(&p);
                } else {
                    total += meta.len();
                }
            }
        }
    }
    total
}

/// Performs a unified filesystem walk across configured roots.
#[must_use]
pub fn scan_hygiene(config: &CleanConfig) -> CleanReport {
    let mut roots: Vec<PathBuf> = config
        .scan_roots
        .iter()
        .chain(config.extra_scan_roots.iter())
        .filter(|p| p.exists())
        .cloned()
        .collect();

    if roots.is_empty() {
        return CleanReport {
            is_elevated: is_elevated(),
            ..Default::default()
        };
    }

    let first_root = roots.remove(0);
    let mut builder = WalkBuilder::new(&first_root);
    for r in &roots {
        builder.add(r);
    }

    builder.hidden(false).parents(false).git_ignore(true);

    let items = Arc::new(Mutex::new(Vec::new()));
    let tracker = Arc::new(Mutex::new(HotspotTracker::new(MAX_HOTSPOTS)));
    let permission_denied = Arc::new(AtomicUsize::new(0));

    let items_clone = Arc::clone(&items);
    let tracker_clone = Arc::clone(&tracker);
    let perm_clone = Arc::clone(&permission_denied);
    let age_threshold = config.age_threshold_days;

    builder.build_parallel().run(|| {
        let items = Arc::clone(&items_clone);
        let tracker = Arc::clone(&tracker_clone);
        let perm = Arc::clone(&perm_clone);

        Box::new(move |result| match result {
            Ok(entry) => {
                let path = entry.path();
                let meta = match entry.metadata() {
                    Ok(m) => m,
                    Err(err) => {
                        if err
                            .io_error()
                            .is_some_and(|e| e.kind() == std::io::ErrorKind::PermissionDenied)
                        {
                            perm.fetch_add(1, Ordering::Relaxed);
                        }
                        return WalkState::Continue;
                    }
                };

                if meta.is_dir() {
                    if is_build_artifact_dir(path) {
                        let size = calculate_dir_size(path);
                        let reason = format!("Build artifact tree: {}", path.display());
                        if let Ok(mut list) = items.lock() {
                            list.push(CleanItem::new(
                                path.to_path_buf(),
                                size,
                                CleanCategory::Artifacts,
                                reason,
                                true,
                            ));
                        }
                        return WalkState::Skip;
                    }
                } else if meta.is_file() {
                    let size = meta.len();
                    if let Ok(mut tr) = tracker.lock() {
                        tr.observe(path, size);
                    }

                    if is_build_artifact_file(path) {
                        if let Ok(mut list) = items.lock() {
                            list.push(CleanItem::new(
                                path.to_path_buf(),
                                size,
                                CleanCategory::Artifacts,
                                "Compiled bytecode artifact".to_string(),
                                false,
                            ));
                        }
                    } else if is_stale_log_file(path, &meta, age_threshold) {
                        let reason = format!("Log older than {age_threshold} days");
                        if let Ok(mut list) = items.lock() {
                            list.push(CleanItem::new(
                                path.to_path_buf(),
                                size,
                                CleanCategory::LogsCache,
                                reason,
                                false,
                            ));
                        }
                    } else if is_stale_cache_entry(path, &meta, age_threshold) {
                        let reason = format!("Cache item older than {age_threshold} days");
                        if let Ok(mut list) = items.lock() {
                            list.push(CleanItem::new(
                                path.to_path_buf(),
                                size,
                                CleanCategory::LogsCache,
                                reason,
                                false,
                            ));
                        }
                    }
                }
                WalkState::Continue
            }
            Err(err) => {
                if err
                    .io_error()
                    .is_some_and(|e| e.kind() == std::io::ErrorKind::PermissionDenied)
                {
                    perm.fetch_add(1, Ordering::Relaxed);
                }
                WalkState::Continue
            }
        })
    });

    let mut final_items = items
        .lock()
        .map_or_else(|_| Vec::new(), |guard| guard.clone());
    let hotspots = tracker
        .lock()
        .map_or_else(|_| Vec::new(), |guard| guard.clone().into_sorted_vec());

    for hot in hotspots {
        if !final_items.iter().any(|i| i.path == hot.path) {
            final_items.push(CleanItem::new(
                hot.path.clone(),
                hot.size_bytes,
                CleanCategory::Hotspots,
                "Disk hotspot (top size consumer)".to_string(),
                false,
            ));
        }
    }

    CleanReport {
        items: final_items,
        skipped_permission_denied: permission_denied.load(Ordering::Relaxed),
        is_elevated: is_elevated(),
    }
}
